import React from "react";
import { Button } from "./ui/button";
import { Dot } from "lucide-react";
import heroImage from "../public/hero-img-1.webp";
import Image from "next/image";
import Link from "next/link";

function HearoSection() {
  return (
    <div className="2xl:flex 2xl:flex-col 2xl:items-center ">
      <div className="bg-gradient-to-r from-[#f8faff] via-[#ffffff] to-[#eef4ff] w-full px-6 mt-0 flex flex-col md:flex md:flex-row xl:justify-center 2xl:w-[1200px] rounded-2xl shadow-sm">
        {/* LEFT TEXT SECTION */}
        <div className="w-[100%] lg:w-[50%] 2xl:w-full flex flex-col justify-center py-10">
          <div className="relative">
            <h3 className="font-bold lg:text-[46px] md:text-[38px] text-[30px] text-[#0B1739] leading-tight">
              IMPRESSIVE RESUMES
            </h3>
            <h3 className="font-semibold lg:text-[46px] md:text-[38px] text-[30px] absolute md:top-10 z-20 text-[#2B2B2B] opacity-90">
              EASY ONLINE BUILDER
            </h3>
          </div>

          <div className="mt-16 flex flex-col gap-y-4 md:w-[90%] lg:w-[100%] text-[#4A4A4A]">
            <span className="flex items-start gap-2">
              <Dot className="text-[#0061F2] w-6 h-6 mt-1" />
              <p>
                Professional out-of-the-box resumes, instantly generated by the
                most advanced resume builder technology available.
              </p>
            </span>
            <span className="flex items-start gap-2">
              <Dot className="text-[#0061F2] w-6 h-6 mt-1" />
              <p>
                Effortless crafting. Real-time preview & pre-written resume
                examples. Dozens of HR-approved resume templates.
              </p>
            </span>
            <span className="flex items-start gap-2">
              <Dot className="text-[#0061F2] w-6 h-6 mt-1" />
              <p>
                Land your dream job with the perfect resume employers are
                looking for!
              </p>
            </span>
            <Link href={'/choesoptions'}>
            <Button className="bg-[#0061F2] hover:bg-[#0050d4] cursor-pointer w-[160px] mt-10 mb-4 md:mb-0 text-white font-medium shadow-md transition-all duration-200 hover:scale-105">
              Build Resume
            </Button>
            </Link>
          </div>
        </div>

        {/* RIGHT IMAGE SECTION */}
        <div className="md:w-[50%] lg:w-[50%] sm:w-[100%] hidden 2xl:w-full md:flex justify-end items-center">
          <div className="relative">
            <div className="absolute -top-6 -left-6 w-20 h-20 bg-[#dce6ff] rounded-full blur-2xl opacity-70"></div>
            <Image
              src={heroImage}
              alt="Resume Builder Hero"
              className="w-[90%] object-contain drop-shadow-2xl"
              priority
            />
          </div>
        </div>
      </div>
    </div>
  );
}

export default HearoSection;
