export const degrees:string[] = [
  "Matriculation (10th)",
  "Intermediate (12th)",
  "FA (Faculty of Arts)",
  "FSc (Faculty of Science)",
  "ICS (Intermediate in Computer Science)",
  "ICom (Intermediate in Commerce)",
  "DAE (Diploma of Associate Engineering)",
  "A-Level",
  "O-Level",
  "Bachelor of Arts (BA)",
  "Bachelor of Science (BSc)",
  "Bachelor of Commerce (BCom)",
  "Bachelor of Business Administration (BBA)",
  "Bachelor of Computer Science (BSCS)",
  "Bachelor of Information Technology (BSIT)",
  "Bachelor of Software Engineering (BSSE)",
  "Bachelor of Engineering (BE)",
  "Bachelor of Architecture (BArch)",
  "Bachelor of Fine Arts (BFA)",
  "Bachelor of Laws (LLB)",
  "Bachelor of Education (BEd)",
  "Bachelor of Pharmacy (BPharm)",
  "Bachelor of Medicine, Bachelor of Surgery (MBBS)",
  "Bachelor of Dental Surgery (BDS)",
  "Bachelor of Nursing (BN)",
  "Bachelor of Agriculture (BSc Agri)",
  "Bachelor of Textile Engineering (BTE)",
  "Bachelor of Environmental Science",
  "Bachelor of Media Studies",
  "Bachelor of Psychology",
  "Bachelor of Sociology",
  "Bachelor of Political Science",
  "Bachelor of Statistics",
  "Bachelor of Mathematics",
  "Bachelor of Physics",
  "Bachelor of Chemistry",
  "Bachelor of English Literature",
  "Master of Arts (MA)",
  "Master of Science (MSc)",
  "Master of Commerce (MCom)",
  "Master of Business Administration (MBA)",
  "Master of Computer Science (MCS)",
  "Master of Information Technology (MIT)",
  "Master of Software Engineering (MSE)",
  "Master of Public Administration (MPA)",
  "Master of Education (MEd)",
  "Master of Laws (LLM)",
  "Master of Architecture (MArch)",
  "Master of Fine Arts (MFA)",
  "Master of Philosophy (MPhil)",
  "Doctor of Philosophy (PhD)",
  "Doctor of Medicine (MD)",
  "Doctor of Dental Surgery (DDS)",
  "Doctor of Pharmacy (PharmD)",
  "Doctor of Business Administration (DBA)"
];
